version: '3.8'
services:
    api:
        build:
            context: ./
            dockerfile: ./docker/api-dev/Dockerfile
        volumes:
            - ./services/api:/usr/template-1/services/api
        ports:
            - 1001:1001
        env_file:
            - ./services/api/.env
        container_name: api
    mysql:
        build:
            context: ./
            dockerfile: ./docker/mysql-dev/Dockerfile
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: template-1
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 3306:3306
        container_name: mysql
volumes:
    mysql-data:
